-- StonkRips: ONE paste into the intended Supabase project's SQL Editor.
-- Generated by npm run launch:sql. Additive: never resets or seeds data.
-- Does not enable automation, packs, swaps, or payouts. Safe to rerun.
begin;
-- StonkRips / Pons v2 hourly automation ledger.
-- Paste this entire file into a NEW Supabase project's SQL editor and run once.

create extension if not exists pgcrypto;

create table if not exists public.pons_epochs (
  id uuid primary key default gen_random_uuid(),
  epoch_key timestamptz not null unique,
  status text not null check (status in (
    'created', 'claiming', 'awaiting_seed', 'holder_drop_swap',
    'holder_drop_send', 'inventory_swap', 'inventory_load',
    'complete', 'no_fees', 'dry_run', 'error'
  )),
  automation_mode text not null check (automation_mode in ('dry-run', 'live')),
  pons_token_address text not null,
  fee_asset_address text not null,
  sweep_tx text,
  claim_tx text,
  preclaim_balance_atoms numeric(78, 0),
  fee_amount_atoms numeric(78, 0),
  holder_drop_budget_atoms numeric(78, 0),
  inventory_budget_atoms numeric(78, 0),
  snapshot_block bigint,
  seed_block bigint,
  seed_hash text,
  winner_address text,
  total_tickets numeric(78, 0),
  winning_ticket numeric(78, 0),
  drop_stock_symbol text,
  drop_stock_address text,
  drop_stock_amount_atoms numeric(78, 0),
  drop_approval_tx text,
  drop_swap_tx text,
  holder_drop_tx text,
  inventory_stock_symbol text,
  inventory_stock_address text,
  inventory_stock_amount_atoms numeric(78, 0),
  inventory_value_usd_micros numeric(78, 0),
  inventory_approval_tx text,
  inventory_swap_tx text,
  pack_approval_tx text,
  inventory_load_tx text,
  error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz
);

create index if not exists pons_epochs_status_created_idx
  on public.pons_epochs (status, created_at desc);

create table if not exists public.pons_audit_events (
  id bigint generated always as identity primary key,
  epoch_id uuid not null references public.pons_epochs(id) on delete restrict,
  epoch_key timestamptz not null,
  previous_status text,
  next_status text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists pons_audit_events_epoch_idx
  on public.pons_audit_events (epoch_id, id);

create table if not exists public.automation_locks (
  lock_name text primary key,
  holder text not null,
  expires_at timestamptz not null,
  updated_at timestamptz not null default now()
);

alter table public.pons_epochs enable row level security;
alter table public.pons_audit_events enable row level security;
alter table public.automation_locks enable row level security;

revoke all on public.pons_epochs from anon, authenticated;
revoke all on public.pons_audit_events from anon, authenticated;
revoke all on public.automation_locks from anon, authenticated;

create or replace function public.audit_pons_epoch_status()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.pons_audit_events (
      epoch_id,
      epoch_key,
      previous_status,
      next_status,
      details
    ) values (
      new.id,
      new.epoch_key,
      null,
      new.status,
      jsonb_strip_nulls(jsonb_build_object(
        'sweep_tx', new.sweep_tx,
        'claim_tx', new.claim_tx,
        'drop_swap_tx', new.drop_swap_tx,
        'holder_drop_tx', new.holder_drop_tx,
        'inventory_swap_tx', new.inventory_swap_tx,
        'inventory_load_tx', new.inventory_load_tx,
        'error', new.error
      ))
    );
  elsif old.status is distinct from new.status or old.error is distinct from new.error then
    insert into public.pons_audit_events (
      epoch_id,
      epoch_key,
      previous_status,
      next_status,
      details
    ) values (
      new.id,
      new.epoch_key,
      old.status,
      new.status,
      jsonb_strip_nulls(jsonb_build_object(
        'sweep_tx', new.sweep_tx,
        'claim_tx', new.claim_tx,
        'drop_swap_tx', new.drop_swap_tx,
        'holder_drop_tx', new.holder_drop_tx,
        'inventory_swap_tx', new.inventory_swap_tx,
        'inventory_load_tx', new.inventory_load_tx,
        'error', new.error
      ))
    );
  end if;
  return new;
end;
$$;

drop trigger if exists pons_epoch_status_audit on public.pons_epochs;
create trigger pons_epoch_status_audit
after insert or update of status, error on public.pons_epochs
for each row execute function public.audit_pons_epoch_status();

create or replace function public.acquire_automation_lock(
  p_holder text,
  p_ttl_seconds integer default 900
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  acquired boolean := false;
begin
  if p_holder is null or length(trim(p_holder)) = 0 then
    raise exception 'holder is required';
  end if;
  if p_ttl_seconds < 30 or p_ttl_seconds > 3600 then
    raise exception 'ttl must be between 30 and 3600 seconds';
  end if;

  insert into public.automation_locks (lock_name, holder, expires_at, updated_at)
  values ('pons-hourly-worker', p_holder, now() + make_interval(secs => p_ttl_seconds), now())
  on conflict (lock_name) do update
    set holder = excluded.holder,
        expires_at = excluded.expires_at,
        updated_at = now()
    where public.automation_locks.expires_at <= now()
       or public.automation_locks.holder = excluded.holder
  returning true into acquired;

  return coalesce(acquired, false);
end;
$$;

create or replace function public.release_automation_lock(p_holder text)
returns void
language sql
security definer
set search_path = public
as $$
  delete from public.automation_locks
  where lock_name = 'pons-hourly-worker' and holder = p_holder;
$$;

revoke all on function public.acquire_automation_lock(text, integer) from public, anon, authenticated;
revoke all on function public.release_automation_lock(text) from public, anon, authenticated;
grant execute on function public.acquire_automation_lock(text, integer) to service_role;
grant execute on function public.release_automation_lock(text) to service_role;

comment on table public.pons_epochs is
  'One idempotent UTC epoch per StonkRips hourly Pons fee cycle.';
comment on table public.pons_audit_events is
  'Append-only status transition evidence for each automation epoch.';

-- Additive migration: run AFTER pons-automation.sql. Does not enable spending.
-- Only verified, settled 20 USDG pack sales enter this separate ledger.

create table if not exists public.pack_reinvestment_epochs (
  id text primary key,
  scope text not null,
  chain_id integer not null check (chain_id = 4663),
  pack_contract text not null,
  treasury text not null,
  epoch_key timestamptz not null,
  scan_from_block bigint not null,
  scan_to_block bigint not null check (scan_to_block >= scan_from_block),
  scan_block_hash text not null,
  budget_atoms text not null check (budget_atoms ~ '^[0-9]+$'),
  status text not null check (status in ('planned', 'complete')),
  created_at timestamptz not null default now(),
  completed_at timestamptz,
  unique (scope, epoch_key)
);
create unique index if not exists pack_reinvestment_one_pending
  on public.pack_reinvestment_epochs (scope) where status = 'planned';

create table if not exists public.pack_sale_receipts (
  chain_id integer not null,
  pack_contract text not null,
  request_id text not null check (request_id ~ '^[1-9][0-9]*$'),
  epoch_id text not null references public.pack_reinvestment_epochs(id),
  transaction_hash text not null,
  block_number bigint not null,
  block_hash text not null,
  amount_atoms text not null check (amount_atoms = '20000000'),
  primary key (chain_id, pack_contract, request_id),
  unique (chain_id, pack_contract, transaction_hash)
);

create table if not exists public.pack_reinvestment_lots (
  id text primary key,
  scope text not null,
  epoch_id text not null references public.pack_reinvestment_epochs(id),
  lot_index integer not null check (lot_index >= 0),
  usd_atoms text not null check (usd_atoms in ('5000000','10000000','15000000','20000000','25000000','30000000','35000000','40000000','50000000')),
  stock_address text,
  stock_symbol text,
  token_amount_atoms text check (token_amount_atoms ~ '^[1-9][0-9]*$'),
  declared_usd_micros text check (declared_usd_micros ~ '^[1-9][0-9]*$'),
  load_transaction text,
  completed_at timestamptz,
  unique (epoch_id, lot_index)
);

-- Signed bytes must NEVER be exposed by a public API. They are stored before
-- broadcast, so uncertain sends/restarts reuse one hash instead of paying twice.
create table if not exists public.pack_reinvestment_transactions (
  id text primary key,
  scope text not null,
  lot_id text not null references public.pack_reinvestment_lots(id),
  step text not null,
  transaction_hash text not null unique,
  serialized_transaction text not null,
  created_at timestamptz not null default now(),
  confirmed_at timestamptz,
  receipt_status text check (receipt_status in ('success', 'reverted')),
  unique (lot_id, step)
);

alter table public.pack_reinvestment_epochs enable row level security;
alter table public.pack_sale_receipts enable row level security;
alter table public.pack_reinvestment_lots enable row level security;
alter table public.pack_reinvestment_transactions enable row level security;
revoke all on public.pack_reinvestment_epochs, public.pack_sale_receipts,
  public.pack_reinvestment_lots, public.pack_reinvestment_transactions from anon, authenticated;
grant select, insert, update on public.pack_reinvestment_epochs, public.pack_sale_receipts,
  public.pack_reinvestment_lots, public.pack_reinvestment_transactions to service_role;

create or replace function public.reserve_pack_reinvestment(p_epoch jsonb, p_receipts jsonb, p_lots jsonb, p_holder text)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  result public.pack_reinvestment_epochs;
  previous public.pack_reinvestment_epochs;
  receipt_total numeric;
  lot_total numeric;
begin
  perform pg_advisory_xact_lock(hashtextextended(p_epoch->>'scope', 0));
  if not exists (select 1 from public.automation_locks where lock_name = 'pons-hourly-worker'
    and holder = p_holder and expires_at > now()) then raise exception 'Automation lease is not held'; end if;
  select * into result from public.pack_reinvestment_epochs where id = p_epoch->>'id';
  if found then return to_jsonb(result); end if;
  if jsonb_array_length(p_receipts) > 2000 or jsonb_array_length(p_lots) > 2000 then raise exception 'Batch too large'; end if;
  select coalesce(sum((value->>'amount_atoms')::numeric),0) into receipt_total from jsonb_array_elements(p_receipts);
  select coalesce(sum((value->>'usd_atoms')::numeric),0) into lot_total from jsonb_array_elements(p_lots);
  if receipt_total <> (p_epoch->>'budget_atoms')::numeric or lot_total <> receipt_total then
    raise exception 'Sale receipts and lot budgets do not reconcile';
  end if;
  if exists (select 1 from jsonb_array_elements(p_receipts) where
    (value->>'block_number')::bigint < (p_epoch->>'scan_from_block')::bigint or
    (value->>'block_number')::bigint > (p_epoch->>'scan_to_block')::bigint) then raise exception 'Receipt outside scan range'; end if;
  if p_epoch->>'scope' <> '4663:' || (p_epoch->>'pack_contract') || ':' || (p_epoch->>'treasury') then raise exception 'Invalid scope'; end if;
  select * into previous from public.pack_reinvestment_epochs where scope = p_epoch->>'scope' order by epoch_key desc limit 1;
  if found and (previous.status <> 'complete' or previous.scan_to_block + 1 <> (p_epoch->>'scan_from_block')::bigint
    or previous.epoch_key >= (p_epoch->>'epoch_key')::timestamptz) then raise exception 'Scan overlaps or previous epoch is incomplete'; end if;
  insert into public.pack_reinvestment_epochs (id, scope, chain_id, pack_contract, treasury, epoch_key,
    scan_from_block, scan_to_block, scan_block_hash, budget_atoms, status, completed_at)
  values (p_epoch->>'id', p_epoch->>'scope', (p_epoch->>'chain_id')::integer,
    p_epoch->>'pack_contract', p_epoch->>'treasury', (p_epoch->>'epoch_key')::timestamptz,
    (p_epoch->>'scan_from_block')::bigint, (p_epoch->>'scan_to_block')::bigint,
    p_epoch->>'scan_block_hash', receipt_total::text, case when lot_total = 0 then 'complete' else 'planned' end,
    case when lot_total = 0 then now() else null end) returning * into result;
  insert into public.pack_sale_receipts (chain_id,pack_contract,request_id,epoch_id,transaction_hash,block_number,block_hash,amount_atoms)
  select result.chain_id,result.pack_contract,value->>'request_id',result.id,
    value->>'transaction_hash',(value->>'block_number')::bigint,value->>'block_hash',value->>'amount_atoms'
  from jsonb_array_elements(p_receipts);
  insert into public.pack_reinvestment_lots (id,scope,epoch_id,lot_index,usd_atoms)
  select value->>'id',result.scope,result.id,(value->>'lot_index')::integer,value->>'usd_atoms'
  from jsonb_array_elements(p_lots);
  return to_jsonb(result);
end;
$$;
revoke all on function public.reserve_pack_reinvestment(jsonb,jsonb,jsonb,text) from public, anon, authenticated;
grant execute on function public.reserve_pack_reinvestment(jsonb,jsonb,jsonb,text) to service_role;

-- Explicit service access also works on projects without default grants.
grant select, insert, update on public.pons_epochs to service_role;
grant select on public.pons_audit_events, public.automation_locks to service_role;
commit;
